---
- name: Directory module
  hosts: all
  vars:
    mydir: "~/example"
  
  tasks: 
    - name: Creating a directory
      ansible.builtin.file:
        path: "{{ mydir }}"
        state: directory
        owner: ansible
        groups: ansible
        mode: '0644'

